"""Portable Storyboard generated by the Get B-rolls CLI."""

# pylint: disable=missing-function-docstring,too-many-locals
# Legado: ocorrências pré-existentes (corpo idêntico ao código anterior à 2.6.0).
#
# pylint: disable=duplicate-code
# Legado: o pylint ancora as mensagens R0801 no último módulo lintado
# (este arquivo), não em quem realmente duplica. Os pares reais são
# `_utf8_output` entre scripts/bump_version.py, scripts/check_anchors.py e
# scripts/gen_skill_mirror.py (três scripts standalone, autossuficientes por
# design, corpo idêntico ao código anterior à 2.6.0).
#
# Nota (R0401, cyclic-import): o pylint imprime a mensagem ancorada neste
# arquivo (o último lintado), mas a supressão que de fato vale
# fica no(s) módulo(s) que participam de cada ciclo — testado empiricamente:
# uma desativação aqui não suprime o achado. Os ciclos reais existem porque um
# import tardio (dentro de função) quebra o ciclo em tempo de execução,
# convenção já documentada no próprio código (ver comentários "avoids a
# runtime<->http/logs import cycle" em runtime.py). Ciclos e onde a
# desativação real está: getbrolls.logs <-> getbrolls.runtime (logs.py,
# runtime.py); getbrolls.http <-> getbrolls.runtime (http.py, runtime.py);
# getbrolls.providers <-> getbrolls.social (providers.py, social.py);
# getbrolls.queue <-> getbrolls.rules (queue.py, rules.py); getbrolls.config
# -> getbrolls.runtime -> getbrolls.http (config.py, mesmo padrão de import
# tardio).

import base64
from html import escape

from . import _paths


def brand_logo():
    encoded = base64.b64encode(_paths.data_path("assets", "brand-logo.png").read_bytes()).decode("ascii")
    return f'<img class="brand-logo" src="data:image/png;base64,{encoded}" alt="Engenheiro de vídeo">'


def render_page(
    items,
    title="Storyboard da coleta",
    subtitle="Veja cada trecho e diga se serve. Leva uns 2 minutos.",
    note=(
        "Aprovar aqui quer dizer “quero esse trecho”, não “posso publicar esse trecho”: antes de "
        "subir seu vídeo, confira a licença de cada fonte pelo link do original em cada card."
    ),
):
    def esc(value):
        return escape(str(value or ""), quote=True)

    templates = []
    gallery = []
    options = []

    def image(path, label):
        # Sem imagem, a miniatura diz o mesmo que a tarja ao lado dela: "só imagem".
        # A explicação comprida vive no painel de detalhe (`rendering.source_card`),
        # onde há espaço e onde a pessoa já parou para ler; no cartão da galeria ela
        # quebrava o layout e repetia a tarja.
        return (
            f'<img loading="lazy" src="{esc(path)}" alt="{esc(label)}">'
            if path
            else '<span class="placeholder">só imagem</span>'
        )

    for i, item in enumerate(items):
        name = esc(item["title"])
        time = esc(item.get("time"))
        narration = esc(item.get("narration"))
        presenter = item.get("presenter")
        left = (
            image(presenter, "Gravação — " + item["title"])
            if presenter
            else '<p class="empty">Sem imagem do seu vídeo aqui.</p>'
        )
        if item.get("gif"):
            left = f'<button class="gif-preview" data-gif="{esc(item["gif"])}" data-poster="{esc(presenter)}" aria-label="Assistir trecho: {esc(item["title"])}" aria-pressed="false">{left}<span>▶ Assistir trecho</span></button>'  # template HTML denso, quebrar mudaria o HTML gerado -- pylint: disable=line-too-long
        has_preview = bool(presenter) and not item.get("no_preview")
        caption = f'<div class="caption-content"><blockquote>“{narration}”</blockquote></div>' if narration else ""
        templates.append(
            f"""<template data-shot id="shot-{i}" data-preview="{"1" if has_preview else "0"}"><figure class="pane presenter"><figcaption><span>{esc(item.get("presenterLabel", "Gravação"))}</span><span>{time}</span></figcaption><div class="image-box">{left}</div></figure><section class="pane material">{item["content"]}</section>{caption}</template>"""  # template HTML denso, quebrar mudaria o HTML gerado -- pylint: disable=line-too-long
        )
        if item.get("gif"):
            thumbnail = f'<img loading="lazy" src="{esc(presenter)}" data-still="{esc(presenter)}" data-animated-thumb="{esc(item["gif"])}" alt="{name}">'  # template HTML denso, quebrar mudaria o HTML gerado -- pylint: disable=line-too-long
        else:
            thumbnail = image(
                presenter or item.get("poster"),
                ("Miniatura da fonte — " if item.get("no_preview") else "Prévia — ") + item["title"],
            )
        badge = '<span class="preview-badge">só imagem</span>' if item.get("no_preview") else ""
        gallery.append(
            f'<button class="shot" data-index="{i}" aria-current="false"><div class="thumbs">{thumbnail}{badge}</div><h3>{name}</h3><div class="time">{time}</div></button>'  # template HTML denso, quebrar mudaria o HTML gerado -- pylint: disable=line-too-long
        )
        options.append(f'<option value="{i}">{name}</option>')
    logo = brand_logo()
    count = len(items)
    quadros = f"{count} quadro" if count == 1 else f"{count} quadros"
    gallery_tools = (
        '<div class="gallery-tools"><div class="storyboard-modes" role="group" aria-label="Animação do storyboard">'
        '<button type="button" data-storyboard-mode="static" aria-pressed="true">Estático</button>'
        '<button type="button" data-storyboard-mode="hover" aria-pressed="false">GIF ao passar o mouse</button>'
        '<button type="button" data-storyboard-mode="on" aria-pressed="false">GIF ligado</button></div>'
        '<label><input type="checkbox" id="pending-only"> Só pendentes</label></div>'
    )
    board = (
        f"""<div class="tools" id="tools"><div class="selection"><button id="prev" aria-label="Quadro anterior">←</button><select id="select" aria-label="Escolher quadro">{"".join(options)}</select><button id="next" aria-label="Próximo quadro">→</button></div><div class="modes" role="group" aria-label="Visualização"><button data-mode="side" aria-pressed="true">Lado a lado</button><button data-mode="material" aria-pressed="false">Só material</button></div></div><div class="viewer" id="viewer"></div><div class="caption" id="caption" aria-live="polite"></div><div class="gallery-head"><h2>Storyboard</h2>{gallery_tools}</div><div class="gallery">{"".join(gallery)}</div>{"".join(templates)}"""  # template HTML denso, quebrar mudaria o HTML gerado -- pylint: disable=line-too-long
        if items
        else '<p class="empty-board">Nada aqui ainda. Volte pra conversa e peça os trechos — eu preencho essa página.</p>'  # template HTML denso, quebrar mudaria o HTML gerado -- pylint: disable=line-too-long
    )
    sub = f'<p class="sub">{esc(subtitle)}</p>' if subtitle else ""
    header = (
        '<header class="artifact-header"><div class="header-shell"><div class="header-top">'
        f'<div class="brand">{logo}<span class="wordmark">engenheiro<span>de vídeo<b>.</b></span></span></div>'
        '<span class="edition">Get B-rolls / Storyboard</span></div>'
        f'<div class="header-project"><div class="header-title"><h1>{esc(title)}</h1>{sub}</div>'
        f'<div class="header-meta"><span>{quadros}</span><span>Storyboard de B-rolls</span></div></div></div></header>'
    )
    film = any(x.get("gif") or (x.get("presenter") and not x.get("no_preview")) for x in items)
    return f'''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><link rel="icon" href="data:,"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GET B-ROLLS — {esc(title)}</title><style>{_paths.data_path("assets", "storyboard.css").read_text(encoding="utf-8")}</style></head><body class="{"film-board" if film else ""}">{header}<main><div class="intro"><span class="count" id="position" hidden></span></div>{board}{f"<footer>{esc(note)}</footer>" if note else ""}<noscript>Ative JavaScript para navegar entre os quadros.</noscript></main><script>{_paths.data_path("assets", "storyboard.js").read_text(encoding="utf-8")}</script></body></html>'''  # template HTML denso, quebrar mudaria o HTML gerado -- pylint: disable=line-too-long
